version: '3.2'
services:
  db:
    container_name: aplans-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=aplans
      - POSTGRES_PASSWORD=change_me
    volumes:
      - db_data:/var/lib/postgresql/data/

  redis:
    container_name: 'redis'
    build:
      context: ./docker/redis
      dockerfile: ./Dockerfile
    restart: always

  app:
    container_name: aplans
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: always
    volumes:
      - aplans_media:/srv/media
    environment:
      - DATABASE_URL=postgres://aplans:change_me@db/aplans
      - CACHE_URL=rediscache://redis:6379
      - STATIC_ROOT=/srv/static
      - LC_CTYPE=C.UTF-8
      - DEBUG
      - ALLOWED_HOSTS
      - COOKIE_PREFIX
      - INTERNAL_IPS
      - SENTRY_DSN
      - SECRET_KEY
      - OIDC_ISSUER_URL
      - OIDC_CLIENT_ID
      - OIDC_CLIENT_SECRET
      - MAILGUN_API_KEY
      - MAILGUN_SENDER_DOMAIN
      - MAILGUN_REGION
    ports:
      - "${HOST_PORT:-8000}:8000"
      - "${UWSGI_SOCKET_PORT:-8001}:8001"
    depends_on:
      - db
      - redis

volumes:
  db_data:
  aplans_media:
