version: '3.3'
services:
  db:
    image: docker.kausal.tech/postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data/

  redis:
    image: docker.kausal.tech/redis

  app:
    image: docker.kausal.tech/watch
    environment:
    volumes:
      - aplans_media:/srv/media
    environment:
      - ENV_FILE
      - DATABASE_URL
      - CACHE_URL=rediscache://redis:6379
      - STATIC_ROOT=/srv/static
      - LC_CTYPE=C.UTF-8
      - DEBUG
      - ALLOWED_HOSTS
      - COOKIE_PREFIX
      - INTERNAL_IPS
      - SENTRY_DSN
      - SECRET_KEY
      - CONFIGURE_LOGGING
      - OIDC_ISSUER_URL
      - OIDC_CLIENT_ID
      - OIDC_CLIENT_SECRET
      - AZURE_AD_CLIENT_ID
      - AZURE_AD_CLIENT_SECRET
      - MAILGUN_API_KEY
      - MAILGUN_SENDER_DOMAIN
      - MAILGUN_REGION
      - EXTRA_INSTALLED_APPS
      - EXTRA_INSTALLED_APPS_URLS
    depends_on:
      - db
      - redis

volumes:
  db_data:
  aplans_media:
