version: '3.3'
services:
  db:
    container_name: aplans-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=aplans
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change_me}

  redis:
    container_name: 'redis'
    build:
      context: ./docker/redis
      dockerfile: ./Dockerfile
    restart: always

  app:
    container_name: aplans
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - EXTRA_PYPI_INDEX
        - EXTRA_INSTALLED_APPS_VERSIONS
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://aplans:change_me@db/aplans}
    ports:
      - "${HOST_PORT:-8000}:8000"
      - "${UWSGI_SOCKET_PORT:-8001}:8001"
