# Generated by Django 5.0.4 on 2024-06-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0125_show_contact_person_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDomainDeployInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('dns_cname', models.CharField(blank=True, max_length=100, null=True)),
                ('dns_status_msg', models.TextField(blank=True, null=True)),
                ('dns_status', models.CharField(blank=True, choices=[('ok', 'All OK'), ('nxdomain', 'Empty response'), ('not_cname', 'Response is not CNAME'), ('invalid_target', 'CNAME target is not valid'), ('other', 'Other error')], max_length=20, null=True)),
                ('tls_expires_at', models.DateTimeField(blank=True, null=True)),
                ('tls_status', models.CharField(blank=True, choices=[('ok', 'All OK'), ('invalid_ca', 'Invalid CA'), ('expiration', 'Certificate expired or about to expire'), ('other', 'Other error')], max_length=20, null=True)),
                ('tls_status_msg', models.TextField(blank=True, null=True)),
                ('http_status', models.CharField(blank=True, choices=[('ok', 'All OK'), ('network', 'Network error'), ('404', 'Page not found (404)'), ('500', 'Internal server error (500)'), ('other', 'Other error')], max_length=20, null=True)),
                ('http_status_msg', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_infos', to='actions.plandomain')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
