name: Build other services

on:
  workflow_call:
    inputs:
      docker_registry:
        required: false
        type: string
        default: ${{ vars.DOCKER_REGISTRY }}
      image_repo:  # watch-backend/elasticsearch
        required: true
        type: string
      image_tag:   # 8
        required: true
        type: string
      dockerfile:   # docker/elasticsearch/Dockerfile
        required: true
        type: string
      context:  # docker/elasticsearch
        required: true
        type: string

jobs:
  elasticsearch:
    name: Build ${{ inputs.image_repo }}
    runs-on: self-hosted
    container:
      image: ghcr.io/actions/actions-runner:latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log into Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker_registry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: remote
          endpoint: tcp://buildkitd:1234
          install: true
          cleanup: true

      - name: Build and push image
        uses: docker/build-push-action@v5
        id: build_push
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: |
            ${{ inputs.image_tag }}
        env:
          BUILDX_GIT_LABELS: full
