name: CI
on: push
jobs:
  build_and_test:
    name: Build Docker container and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building Docker containers
        run: |
          docker-compose build
      - name: Starting Postgres and Redis
        run: |
          docker-compose up -d db redis
      - name: Running pytest unit tests
        run: docker-compose run --rm --entrypoint '' app pytest
      - name: Stopping Postgres and Redis
        run: |
          docker-compose down db redis
