name: CI
on: push
jobs:
  build_and_test:
    name: Build Docker container and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building Docker containers
        run: |
          docker-compose build
      - name: Running pytest unit tests
        run: docker-compose run --entrypoint '' app pytest 
